/**
 *base on JQuery
 *menusList 一级菜单
 *menusTop 顶级横向菜单
 *menusMap 子菜单
 *@author Rudy Zou
 */
var _menus={menusFirst:[{"name":"首页","icon":"icon-dashboard","id":"ZZZZZ","leaf":1,"level":1,"url":"http://www.baidu.com","target":""}
						,{"name":"购货管理","icon":"icon-text-width","id":"AAAAA","leaf":0,"level":1,"url":"","target":""}
						,{"name":"销货管理","icon":"icon-desktop","id":"BBBBB","leaf":0,"level":1,"url":"","target":""}
						,{"name":"仓库管理","icon":"icon-list","id":"CCCCC","leaf":0,"level":1,"url":"","target":""}
						,{"name":"资金管理","icon":"icon-edit","id":"DDDDD","leaf":0,"level":1,"url":"","target":""}
						,{"name":"报表管理","icon":"icon-list-alt","id":"FFFFF","leaf":0,"level":1,"url":"","target":""}
						,{"name":"系统管理","icon":"icon-picture","id":"GGGGG","leaf":0,"level":1,"url":"","target":""}
						]
			,menusTop:[]
			,menusMap:{"AAAAA":[
										{"name":"购货订单","icon":"icon-leaf","id":"AAAAAA","uparentid":"AAAAA","leaf":1,"level":2,"url":"","target":""}
										,{"name":"购货订单记录","icon":"icon-pencil","id":"AAAAAAB","uparentid":"AAAAA","leaf":1,"level":2,"url":"","target":""}
										,{"name":"购货单","icon":"icon-pencil","id":"AAAAAAC","uparentid":"AAAAA","leaf":1,"level":2,"url":"","target":""}
										,{"name":"购货记录","icon":"icon-pencil","id":"AAAAAAD","uparentid":"AAAAA","leaf":1,"level":2,"url":"","target":""}
										]
						,"BBBBB":[
										{"name":"销货订单","icon":"icon-leaf","id":"BBBBBA","uparentid":"BBBBB","leaf":1,"level":2,"url":"","target":""}
										,{"name":"销货订单记录","icon":"icon-pencil","id":"BBBBBB","uparentid":"BBBBB","leaf":1,"level":2,"url":"","target":""}
										,{"name":"销货单","icon":"icon-pencil","id":"BBBBBC","uparentid":"BBBBB","leaf":1,"level":2,"url":"","target":""}
										,{"name":"销货记录","icon":"icon-pencil","id":"BBBBBD","uparentid":"BBBBB","leaf":1,"level":2,"url":"","target":""}
										]
						,"CCCCC":[
										{"name":"调拨单","icon":"icon-leaf","id":"CCCCCA","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"调拨记录","icon":"icon-pencil","id":"CCCCCB","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"盘点","icon":"icon-pencil","id":"CCCCCC","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"其他入库","icon":"icon-pencil","id":"CCCCCD","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"其他入库记录","icon":"icon-pencil","id":"CCCCCE","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"其他出库","icon":"icon-pencil","id":"CCCCCF","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"其他出库记录","icon":"icon-pencil","id":"CCCCCG","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"成本调整单","icon":"icon-pencil","id":"CCCCCH","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										,{"name":"成本调整记录","icon":"icon-pencil","id":"CCCCCI","uparentid":"CCCCC","leaf":1,"level":2,"url":"","target":""}
										]
						,"DDDDD":[
										{"name":"收款单","icon":"icon-leaf","id":"DDDDDA","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										,{"name":"收款记录","icon":"icon-pencil","id":"DDDDDB","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										,{"name":"付款单","icon":"icon-pencil","id":"DDDDDC","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										,{"name":"付款单记录","icon":"icon-pencil","id":"DDDDDD","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										,{"name":"核销单","icon":"icon-pencil","id":"DDDDDE","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										,{"name":"核销记录","icon":"icon-pencil","id":"DDDDDF","uparentid":"DDDDD","leaf":1,"level":2,"url":"","target":""}
										]
						,"GGGGG":[{"name":"基础数据管理","icon":"icon-double-angle-right","id":"GGGGGA","uparentid":"GGGGG","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"用户管理","icon":"icon-leaf","id":"GGGGGAA","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"供应商管理","icon":"icon-pencil","id":"GGGGGAB","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"客户管理","icon":"icon-pencil","id":"GGGGGAC","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"仓库管理","icon":"icon-pencil","id":"GGGGGAD","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"商品管理","icon":"icon-pencil","id":"GGGGGAE","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"供货地址管理","icon":"icon-pencil","id":"GGGGGAF","uparentid":"GGGGGA","leaf":1,"level":3,"url":"","target":""}
										]}
							  ,{"name":"辅助数据管理","icon":"icon-double-angle-right","id":"GGGGGB","uparentid":"GGGGG","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"计量单位管理","icon":"icon-leaf","id":"GGGGGBA","uparentid":"GGGGGB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"商品类目管理","icon":"icon-pencil","id":"GGGGGBB","uparentid":"GGGGGB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"客户类别管理","icon":"icon-pencil","id":"GGGGGBC","uparentid":"GGGGGB","leaf":1,"level":3,"url":"","target":""}	
										,{"name":"结算方式管理","icon":"icon-pencil","id":"GGGGGBE","uparentid":"GGGGGB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"供应商类别管理","icon":"icon-pencil","id":"GGGGGBD","uparentid":"GGGGGB","leaf":1,"level":3,"url":"","target":""}
										]}
							  ,{"name":"系统高级设置","icon":"icon-double-angle-right","id":"GGGGGC","uparentid":"GGGGG","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"权限管理","icon":"icon-leaf","id":"GGGGGCA","uparentid":"GGGGGC","leaf":1,"level":3,"url":"","target":""}
										,{"name":"操作日志","icon":"icon-pencil","id":"GGGGGCB","uparentid":"GGGGGC","leaf":1,"level":3,"url":"","target":""}
										,{"name":"系统参数","icon":"icon-pencil","id":"GGGGGCC","uparentid":"GGGGGC","leaf":1,"level":3,"url":"","target":""}
										,{"name":"菜单管理","icon":"icon-pencil","id":"GGGGGCE","uparentid":"GGGGGC","leaf":1,"level":3,"url":"/sys/menu/treeList","target":""}
										,{"name":"报表模板","icon":"icon-pencil","id":"GGGGGCD","uparentid":"GGGGGC","leaf":1,"level":3,"url":"","target":""}
										
										]}
					          ],
						"FFFFF":[{"name":"采购报表","icon":"icon-double-angle-right","id":"FFFFFA","uparentid":"FFFFF","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"采购订单跟踪报表","icon":"icon-leaf","id":"FFFFFAA","uparentid":"FFFFFA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"采购明细表","icon":"icon-pencil","id":"FFFFFAB","uparentid":"FFFFFA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"采购汇总表<BR/>（按商品）","icon":"icon-pencil","id":"FFFFFAC","uparentid":"FFFFFA","leaf":1,"level":3,"url":"","target":""}
										,{"name":"采购汇总表<BR/>（按供应商）","icon":"icon-pencil","id":"FFFFFAD","uparentid":"FFFFFA","leaf":1,"level":3,"url":"","target":""}
										]}
							  ,{"name":"销售报表","icon":"icon-double-angle-right","id":"FFFFFB","uparentid":"FFFFF","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"销售订单跟踪报表","icon":"icon-leaf","id":"FFFFFBA","uparentid":"FFFFFB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"销售明细表","icon":"icon-pencil","id":"FFFFFBB","uparentid":"FFFFFB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"销售汇总表<BR/>（按商品）","icon":"icon-pencil","id":"FFFFFBC","uparentid":"FFFFFB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"销售汇总表<BR/>（按客户）","icon":"icon-pencil","id":"FFFFFBD","uparentid":"FFFFFB","leaf":1,"level":3,"url":"","target":""}
										,{"name":"往来单位欠款表","icon":"icon-pencil","id":"FFFFFBE","uparentid":"FFFFFB","leaf":1,"level":3,"url":"","target":""}
										]}
							  ,{"name":"仓存报表","icon":"icon-double-angle-right","id":"FFFFFC","uparentid":"FFFFF","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"商品库存余额表","icon":"icon-leaf","id":"FFFFFCA","uparentid":"FFFFFC","leaf":1,"level":3,"url":"","target":""}
										,{"name":"商品收发明细表","icon":"icon-pencil","id":"FFFFFCB","uparentid":"FFFFFC","leaf":1,"level":3,"url":"","target":""}
										,{"name":"商品收发汇总","icon":"icon-pencil","id":"FFFFFCC","uparentid":"FFFFFC","leaf":1,"level":3,"url":"","target":""}
										]}
								,{"name":"资金报表","icon":"icon-double-angle-right","id":"FFFFFD","uparentid":"FFFFF","leaf":0,"level":2,"url":"","target":"","children":[
										{"name":"现金银行报表","icon":"icon-leaf","id":"FFFFFDA","uparentid":"FFFFFD","leaf":1,"level":3,"url":"","target":""}
										,{"name":"应付账款明细表","icon":"icon-pencil","id":"FFFFFDB","uparentid":"FFFFFD","leaf":1,"level":3,"url":"","target":""}
										,{"name":"应收账款明细表","icon":"icon-pencil","id":"FFFFFDC","uparentid":"FFFFFD","leaf":1,"level":3,"url":"","target":""}
										,{"name":"客户对账单","icon":"icon-pencil","id":"FFFFFDD","uparentid":"FFFFFD","leaf":1,"level":3,"url":"","target":""}
										,{"name":"供应商对账单","icon":"icon-pencil","id":"FFFFFDE","uparentid":"FFFFFD","leaf":1,"level":3,"url":"","target":""}
										]}
					          ]
			         }
		 };
var _settings={menus:_menus};
